sonar.projectKey=uqam-mgl7760-groupe-5-hiver-2026-thierry-meriem-gwendal_opensource-together
sonar.organization=uqam-mgl7760-groupe-5-hiver-2026-thierry-meriem-gwendal

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**
