name: SonarCloud Scan

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Facultatif mais recommandé si tu veux la couverture de tests
      - name: Run tests
        run: npm test --if-present

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECTKEY: "UQAM MGL7760 Groupe 5 Hiver 2026" 
          SONAR_ORGANIZATION: "uqam-mgl7760-groupe-5-hiver-2026-thierry-meriem-gwendal"
